# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD$

PORTNAME=	hscolour
PORTVERSION=	1.24.4
PORTREVISION=	3
PORTEPOCH=	1
CATEGORIES=	print haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Colourise Haskell code

LICENSE=	GPLv2

EXECUTABLES=	HsColour

.include "${.CURDIR}/../../lang/ghc/bsd.new-cabal.mk"
.include <bsd.port.mk>
