# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD$

PORTNAME=	brainfuck
PORTVERSION=	0.1.0.3
PORTREVISION=	5
CATEGORIES=	lang haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Brainfuck interpreter

LICENSE=	GPLv2

EXECUTABLES=	bf

.include "${.CURDIR}/../../lang/ghc/bsd.new-cabal.mk"
.include <bsd.port.mk>
