# Created by: obraun@FreeBSD.org
# $FreeBSD$

PORTNAME=	cpphs
PORTVERSION=	1.20.8
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Liberalised re-implementation of cpp, the C pre-processor

LICENSE=	LGPL21

USES=		cabal

USE_CABAL=	polyparse-1.12.1

.include <bsd.port.mk>
