# $FreeBSD$

PORTNAME=	DAV
PORTVERSION=	1.3.3
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	RFC 4918 WebDAV support

LICENSE=	GPLv3

EXECUTABLES=	hdav

FLAGS_ENABLE=	network-uri

.include "${.CURDIR}/../../lang/ghc/bsd.new-cabal.mk"
.include <bsd.port.mk>
