# $FreeBSD$

PORTNAME=	hasktags
PORTVERSION=	0.71.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Produces ctags "tags" and etags "TAGS" files for Haskell programs

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.new-cabal.mk"
.include <bsd.port.mk>
