# $FreeBSD$

PORTNAME=	ghc-events
PORTVERSION=	0.8.0.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library and tool for parsing .eventlog files from GHC

LICENSE=	BSD3CLAUSE

USE_CABAL=	primitive-0.6.4.0_1 vector-0.12.0.2

.include "${.CURDIR}/../../lang/ghc/bsd.new-cabal.mk"
.include <bsd.port.mk>
