# $FreeBSD$

PORTNAME=	ghc-events
PORTVERSION=	0.8.0.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library and tool for parsing .eventlog files from GHC

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.new-cabal.mk"
.include <bsd.port.mk>
