# $FreeBSD$

PORTNAME=	bytestring-nums
PORTVERSION=	0.3.6
PORTREVISION=	16
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse numeric literals from ByteStrings

LICENSE=	BSD3CLAUSE

CABAL_FLAGS=	cli
EXECUTABLES=	spoj-eugene
BUILD_TARGET=	exe:spoj-eugene

.include "${.CURDIR}/../../lang/ghc/bsd.new-cabal.mk"
.include <bsd.port.mk>
