# $FreeBSD$

PORTNAME=	hspec-discover
PORTVERSION=	2.6.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Automatically discover and run Hspec tests

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.new-cabal.mk"
.include <bsd.port.mk>
